spring:
  data:
    redis:
      host: @redis.host@
      port: @redis.port@
      password: @redis.password@
      database: @redis.database@
      connect-timeout: @redis.connect.timeout@
      timeout: @redis.timeout@
      lettuce:
        pool:
          # 最大连接数，负值表示没有限制，默认8
          max-active: @redis.lettuce.pool.max-active@
          # 最大阻塞等待时间，负值表示没限制，默认-1
          max-wait: @redis.lettuce.pool.max-wait@
          # 最大空闲连接，默认8
          max-idle: @redis.lettuce.pool.max-idle@
          # 最小空闲连接，默认0
          min-idle: @redis.lettuce.pool.min-idle@
          enabled: true